stages:
  - build
  - deploy

build:
  image:
    name: pandoc/latex:latest
    entrypoint: [""]
  stage: build
  script:
    - apk add make
    - make pdfs
    - make htmls
  artifacts:
    paths:
      - "*.pdf"
      - "*.html"

build-latex:
  image: aergus/latex:latest
  stage: build
  before_script:
    - apt update
    - apt install make -y
  script:
    - make progress-report
    - mv progress_report/build/main.pdf progress_report.pdf
    - make document-visualization
    - document_visualization/build/main.pdf document_visualization.pdf
  artifacts:
    paths:
      - "*.pdf"

pages:
  stage: deploy
  script:
    - mkdir public
    - cp *.pdf public/
    - cp *.html public/
    - mv public/README.md.html public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
