stages:
  - build
  - deploy

build:
  image:
    name: pandoc/latex:latest
    entrypoint: [""]
  stage: build
  script:
    - apk add make
    - make all
  artifacts:
    paths:
      - "*.pdf"

pages:
  stage: deploy
  script:
    - mkdir public
    - cp *.pdf public/
  artifacts:
    paths:
      - public
  only:
    - master
